# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: partywave
services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: partywave
      POSTGRES_USER: partywave
      POSTGRES_PASSWORD: partywave
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
